steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'
      - './scraper'
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'
    id: 'push-image'

  # Deploy multiple Cloud Run Jobs with different page ranges
  
  # Delete existing jobs (if they exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'delete'
      - 'hm-scraper-job-1'
      - '--region=europe-west1'
      - '--quiet'
    id: 'delete-existing-job-1'
    allowFailure: true

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'delete'
      - 'hm-scraper-job-2'
      - '--region=europe-west1'
      - '--quiet'
    id: 'delete-existing-job-2'
    allowFailure: true

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'delete'
      - 'hm-scraper-job-3'
      - '--region=europe-west1'
      - '--quiet'
    id: 'delete-existing-job-3'
    allowFailure: true

  # Create Job 1: Pages 1-10
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'hm-scraper-job-1'
      - '--image=gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'
      - '--region=europe-west1'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--task-timeout=1800'
      - '--max-retries=3'
      - '--parallelism=1'
      - '--set-env-vars=START_PAGE=1,END_PAGE=3'
    id: 'deploy-job-1'

  # Create Job 2: Pages 10-20
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'hm-scraper-job-2'
      - '--image=gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'
      - '--region=europe-west1'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--task-timeout=1800'
      - '--max-retries=3'
      - '--parallelism=1'
      - '--set-env-vars=START_PAGE=3,END_PAGE=6'
    id: 'deploy-job-2'

  # Create Job 3: Pages 20-30
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'hm-scraper-job-3'
      - '--image=gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'
      - '--region=europe-west1'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--task-timeout=1800'
      - '--max-retries=3'
      - '--parallelism=1'
      - '--set-env-vars=START_PAGE=6,END_PAGE=9'
    id: 'deploy-job-3'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hm-scraper:$BUILD_ID'

options:
  machineType: 'E2_HIGHCPU_8'